# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulam', '0002_auto_20171018_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
